### ISSUE TITLE
Bug in text method of dataTables.buttons.js

### ISSUE THREAD

**Issue by rboykin** [DataTables/Buttons#50]
Bug recently introduced here:  https://github.com/DataTables/Buttons/blob/master/js/dataTables.buttons.js#L330

var linerTag = typeof idx === 'string' && idx.indexOf( '-' ) ?

Code should instead be comparing the result of idx.indexOf('-') !== -1

**Comment by rboykin** [comment]
Even with this line fixed in my local environment using a collection of flash buttons, I still fail on the subsequent line:

this.c.dom.collection.buttonLiner.tag

as buttonLiner is not set.

**Comment by DataTables** [comment]
Oops! Thanks for pointing that out. Fixed now.

**Comment by rboykin** [comment]
This just moved the failing code.  It still fails on the first flash button within a collection as collection.buttonLiner is still not defined and the reference to .tag within the modified conditional fails.

**Comment by rboykin** [comment]
My collection of buttons defined like this

```
{
    "extend": "collection",
    "text":   "Save",
    "buttons":    
    [
        "csv",
        "excel",
        "pdf"
    ]
}
```

**Comment by DataTables** [comment]
Doh - sorry. i was looking at the wrong part of the code when I checked to see if it could be set at all or  not.

**Comment by rboykin** [comment]
That seems to fix it.  Thanks for the iterations.
